### ISSUE TITLE
.toContain doesn't support strings

### ISSUE THREAD

**Issue by oscarotero** [allain/expect#12]
According with the docs: https://jestjs.io/docs/en/expect#tocontainitem

> .toContain can also check whether a string is a substring of another string.

This implementation only checks arrays, and throw an error on passing a string.

**Comment by allain** [comment]
Thanks for spotting it. On it.

**Comment by allain** [comment]
Done. Tagged as v0.2.9. Sorry it took so long, I hadn't seen this message amongst the horde of dependabot messages.
