### ISSUE TITLE
Error due to - std versions prefixed with 'v' were deprecated recently.

### ISSUE THREAD

**Issue by singla-shivam** [allain/expect#14]
Getting error due to **_std versions prefixed with 'v' were deprecated recently_**.

**Code (file - test.ts)**
```typescript
import { expect } from 'https://deno.land/x/expect/mod.ts'
```

**Command**
`deno test _test.ts --reload`

**Error**
```
Download https://deno.land/x/expect/mod.ts
Warning Implicitly using latest version (v0.2.5) for https://deno.land/x/expect/mod.ts
Download https://deno.land/x/expect@v0.2.5/mod.ts
Download https://deno.land/x/expect@v0.2.5/mock.ts
Download https://deno.land/x/expect@v0.2.5/expect.ts
Download https://deno.land/std@v0.50.0/testing/asserts.ts
Download https://deno.land/x/expect@v0.2.5/matchers.ts
Warning std versions prefixed with 'v' were deprecated recently. Please change your import to https://deno.land/std@0.50.0/testing/asserts.ts (at https://deno.land/std@v0.50.0/testing/asserts.ts)
error: Import 'https://deno.land/std@v0.50.0/testing/asserts.ts' failed: 404 Not Found
    at https://deno.land/x/expect@v0.2.5/expect.ts:4:0
```

**Comment by allain** [comment]
Interesting that particular string std@v0.50.0 isn't in the code base. I'm not sure how to proceed on this one.

**Comment by singla-shivam** [comment]
Ah, I checked the code, it's not there. It's removed the most recent commit. Could you please roll out a new version for it?

**Comment by allain** [comment]
done. I think I created a new tag v0.2.6 and I have webhooks setup on the github repo.

Let me know if that did it for you.

**Comment by singla-shivam** [comment]
Oh, for some reason, Deno was not showing the latest version. It's there now and worked. Thank you very much.
