### ISSUE TITLE
`toBeRejectedWith` helper

### ISSUE THREAD

**Issue by talentlessguy** [allain/expect#15]
would be cool to have it for testing promises

**Comment by tommywalkie** [comment]
@talentlessguy This may not answer your question, but it is worth noting that promise errors can be tested using the provided and `rejects.toThrow` matcher, through it wasn't _very clear_ in the README, I could find a bit more about it here:

https://github.com/allain/expect/blob/efdb60b6eee29e0def621b12e61a32c3ea81a638/expect_test.ts#L400

Usage example (regex-based):

```typescript
expect(somePromise()).rejects.toThrow(/.*there should be this error message.*/gi);
```

**Comment by allain** [comment]
Not going to fix this because expect(somePromise()).resolve.toEqual(...) is also supported.
