### ISSUE TITLE
`expect()` only works on `Promise`, not `PromiseLike`

### ISSUE THREAD

**Issue by cowboyd** [allain/expect#24]
Not all awaitables are promises. In fact, the runtime calls the `then()` method whether or not the object is an instance of `Promise` or not. `expect()` checks to see not if there is a `then` method, but uses `instanceof Promise`.

I'm happy to fix this if you would accept a pull request.

**Comment by allain** [comment]
Please go ahead. I definitely would accept it.

**Comment by cowboyd** [comment]
@allain Submitted #25 and #26 which make working with async much nicer. Let me know if there is anything you would change!
