### ISSUE TITLE
This outdated repo is the top Google search result for deno expect

### ISSUE THREAD

**Issue by dandv** [allain/expect#32]
Please consider deprecating or removing the package, as it may easily confuse new Deno users.

![image](https://github.com/user-attachments/assets/bc9e1920-177d-44ea-a115-b5f6ec35b595)

**Comment by allain** [comment]
Done.

Added wording to README.md.
Added deprecation topic on github.
Bumped the tag so that deno.land sees it.

Will that do?

**Comment by dandv** [comment]
Thank you! That'll do. Feel free to [archive the repo](https://docs.github.com/en/repositories/archiving-a-github-repository/archiving-repositories) if you'd like.
